### ISSUE TITLE
Reglas y recomendaciones para contribuir

### ISSUE THREAD

**Issue by hectorpalmatellez** [devschile/huemul#1]

**Comment by juanbrujo** [comment]
que tiene de malo el actual? 🤔

**Comment by hectorpalmatellez** [comment]
El issue fue cuando recién hicimos el fork, el de ahora está bueno. No sé si le cambiaría algo, en realidad.

**Comment by iamravenous** [comment]
Más que eso, faltaría un **_CONTRIBUTING.md_**.

**Comment by hectorpalmatellez** [comment]
Bacán eso del contributing, ¿renombramos este issue a eso?  :thought_balloon:

**Comment by juanbrujo** [comment]
zi
