### ISSUE TITLE
arreglar que los nuevos puedan tener karma

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#106]

**Comment by juanbrujo** [comment]
de paso, cata--

**Comment by lgaticaq** [comment]
`robot.enter (res) ->` en que caso ocurre ese evento? Tenia entendido que eso se disparaba cuando un usuario nuevo ingresa

**Comment by juanbrujo** [comment]
se da por cerrado esto? :gmq: ?

**Comment by gmq** [comment]
Si, #115 lo arregla.

**Comment by juanbrujo** [comment]
buen trabajo 🍻  gmq++

pd. cata-- por no valorar estas mejoras a :sadhuemul:

**Comment by juanbrujo** [comment]
¿ven que :cata: no nos valora? :sadhuemul:
