### ISSUE TITLE
Mejora: que no se repita el random de regalos a sugerir

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#118]
https://github.com/devschile/huemul/blob/master/scripts/regalador.js#L49

**Comment by raerpo** [comment]
Me gustaría ayudar con esto pero el script que pusiste ya no existe. ¿Está en otra parte?

**Comment by juanbrujo** [comment]
creo que lo borramos por fome

**Comment by lgaticaq** [comment]
https://github.com/devschile/huemul/commit/037867b071d95662ce7be1f66c5aad427bf61b9f#diff-a9bf08961604fa538223264a64e16710

**Comment by jlobos** [comment]
Se borro porque usaba la función `eval`, dejaba ejecutar código arbitrario en el servidor 🔥

**Comment by juanbrujo** [comment]
veldá! y arreglarlo era más fome que usarlo así que 👠 💥
