### ISSUE TITLE
Crear comando para listar portadas disponibles

### ISSUE THREAD

**Issue by lgaticaq** [devschile/huemul#133]
Por 2 motivos, usabilidad y para que hubot no muestre el INFO de documentación deprecada en ese script

**Comment by juanbrujo** [comment]
apoyo y es facil de hacerse `hubot portada lista(do)`

**Comment by juanbrujo** [comment]
hecho en https://github.com/devschile/huemul/pull/141/commits/461c96da989ab11eecd189363df5d8e594d7d31a se cierra
