### ISSUE TITLE
Idea: Pegas informales por email posteadas en #pegas

### ISSUE THREAD

**Issue by lgaticaq** [devschile/huemul#135]
La idea es saltarse el "tengo un amigo/a que busca X personas con X experiencia, bla bla". La idea es que se envíe un email tipo, o quizás un formulario o un incluso un form en el landing de devschile. Luego de eso se cree un post en el canal #pegas. Si se ponen mas ambiciosos se podría pedir un aporte o derechamente cobrar algo por ese servicio.

**Comment by juanbrujo** [comment]
Deja procesar el modelo de negocio de esta idea 💡

**Comment by quest** [comment]
quizás un tweet a la cuenta de devschile o a huemul puede ser para publicar un empleo.

**Comment by juanbrujo** [comment]
ya estoy en esto, será un nuevo medio de ingreso de donaciones.
