### ISSUE TITLE
Mejora: Poner mas bella la pagina del karma todos

### ISSUE THREAD

**Issue by lgaticaq** [devschile/huemul#139]
Actualmente esta así.
![selecci n_016](https://cloud.githubusercontent.com/assets/661958/21458451/5608cc2c-c92e-11e6-9f7d-511c056d1f85.png)

También podrían destacarse quien tiene mas y quien tiene menos al principio de la pagina.

**Comment by juanbrujo** [comment]
necesito ayuda con esto, deberíamos definir un theme base y todos los scripts output usarlo, cada uno con su contenido. el theme base en realidad podría ser el de #agencias pero hay que ordenar el _view_ y _public_ . ayura.

**Comment by lgaticaq** [comment]
Si se trata de organizar el proyecto puedo ayudar. También creo que de no presentarse algún otro tema que se quede el de agencias como el base oficial para huemul

**Comment by juanbrujo** [comment]
@lgaticaq ese nomás para no darle vueltas. habría que ordenar lo archivos y los 2 scripts que creo usan un output: agencias.coffee y karma.coffee, y generar una base para que otros puedan utilizarlo.

**Comment by jlobos** [comment]
se podría agregar `firebase` al script de karma y mostrar en realtime en la pagina principal :zap:

**Comment by juanbrujo** [comment]
listo en https://github.com/devschile/huemul/pull/342/commits/5489ab57ec7c4989123faf1855e38e228b58039f
