### ISSUE TITLE
idea: script con las últimas noticias, de algún feed creíble de Chile e internacional (reuters, bbc, afp...)

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#154]

**Comment by lgaticaq** [comment]
Mientras solo aparezca cuando se invoque mediante un comando no hay drama

**Comment by juanbrujo** [comment]
sipo, un `huemul noticias chile|mundo`

**Comment by jlobos** [comment]
se podrían sacar artículos de [Betazeta](https://github.com/jlobos/betazeta) (Fayerwayer, Niubie...)

`huemul noticias chile`
```js
betazeta.articles({ localization: 'cl' }).then(articles => {
  console.log(articles)
})
```

`huemul noticias chino rios`
```js
betazeta.search({ q: 'chino rios', site: 'betazeta' }).then(res => {
  console.log(res)
})
```

**Comment by jlobos** [comment]
[http://search.24horas.cl/search/?q=santiago](http://search.24horas.cl/search/?q=santiago) escupe un `json` con los matches de la query `q=santiago`

**Comment by juanbrujo** [comment]
me parece @jlobos quieres implementarlo tu?ese seria nacional, faltaria uno internacional.

**Comment by juanbrujo** [comment]
aqui internacional http://search.24horas.cl/search/?q=bbc

**Comment by jlobos** [comment]
@juanbrujo ya :ok_hand:

**Comment by jlobos** [comment]
https://github.com/devschile/huemul/pull/225

**Comment by juanbrujo** [comment]
me retiro porque vuelvo a Stgo despues de las 16 hrs
