### ISSUE TITLE
huemul-recetas ya no trae resultados válidos

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#164]
probablemente el scraper está fallando.

**Comment by juanbrujo** [comment]
:gmq: sabes porque puede estar pasando esto?

```
huemul> huemul receta choclo
huemul> Shell me quiso maltratar. No lo voy a pescar por 5 minutos.
```

**Comment by gmq** [comment]
No estoy seguro, si no están definidas las palabras prohibidas no debería encontrar nada. 🤔

**Comment by juanbrujo** [comment]
fixed en https://github.com/devschile/huemul/pull/177
