### ISSUE TITLE
Respuesta de karma como mensaje privado

### ISSUE THREAD

**Issue by lgaticaq** [devschile/huemul#171]
En vista del _spam_ generado por karma creo que es sano enviar como mensaje privado, por lo menos, el mensaje de colisión de nombres el dar karma con una sola letra (`a++`).

**Comment by dukuo** [comment]
+1, si nadie dijo yo lo hago después de almuerzo

**Comment by lgaticaq** [comment]
:+1: dale @dukuo

**Comment by devjunkORG** [comment]
Tal vez seria bueno que el mensaje simplemente no incluya los nombres que colisionan. Que diga algo como "He encontrado n usuarios que contienen <string>. Se mas especifico."

**Comment by lgaticaq** [comment]
Igual es necesario saber, la idea es no escribir el nombre completo del usuario para que no llegue una notificación por su nombre.

**Comment by gmq** [comment]
No sé si valga la pena mostrar todas las posibilidades si Slack igual tira la lista si está autocompletando.

**Comment by gmq** [comment]
Aparte que ahora no tira _todos_ los usuarios posibles, solo los que existen en el cerebro de hubot.

**Comment by iamravenous** [comment]
¿No sería mejor que hubiese un mínimo de caracteres requeridos para dar karma? Porque aunque te lo envíe como mensaje privado, de igual manera hará todos esos request a la API de Slack.

@gmq Pero ya no funciona el karma con `@`, así que difícil que te autocomplete, cuando lo estás escribiendo así no más.

**Comment by lgaticaq** [comment]
hay un usuario que se llama `m`

**Comment by juanbrujo** [comment]
:ban: a @m

**Comment by lgaticaq** [comment]
@iamravenous haciendo eso igual va a spamear :jaime: la idea es que se cague el solo

**Comment by iamravenous** [comment]
@lgaticaq Sí, igual estoy de acuerdo con enviarlo al mensaje privado, de por sí el script de karma genera harto spam. Mi punto iba más por no saturar tanto al animal, @gmq había mencionado que algunos request habían quedado en el aire por el limite de la API de Slack.

No te podí llamar @m :ban:

**Comment by dukuo** [comment]
Ban Jaime y @m lol

**Comment by juanbrujo** [comment]
en que quedó esto?

**Comment by lgaticaq** [comment]
@dukuo tenía ganas de hacerlo no se si ya empiezo, pero igual podría enviar el PR con el anti-jaime-spam

**Comment by dukuo** [comment]
En esto estoy ahora, https://www.youtube.com/watch?v=LdAXw9ZkwJo

**Comment by juanbrujo** [comment]
creo que esto está listo no?

**Comment by lgaticaq** [comment]
Resuelto en #183
