### ISSUE TITLE
con la migración como va a quedar el panel de gifs de #agencias?

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#174]
https://huemul.herokuapp.com/agencias/all

**Comment by lgaticaq** [comment]
Creo que actualmente no hay dominio apuntando al droplet, así que por mientras quedaría como `http://104.131.105.95/agencias/all`, pero creo que antes hay que hacer algo con dokku porque no esta respondiendo

**Comment by juanbrujo** [comment]
🤔  y si migramos el sitio tambien a ese droplet? pesa 130kb con cuea

**Comment by juanbrujo** [comment]
así apuntamos el dominio y ✨

**Comment by lgaticaq** [comment]
:+1:

**Comment by juanbrujo** [comment]
cuando quieran lo hacimol

**Comment by juanbrujo** [comment]
está hecha la migración del DNS al droplet del :huemul:

**Comment by juanbrujo** [comment]
y creo que esto tb quedó listo con el PR de :leonardo: https://github.com/devschile/huemul/pull/184 falta que :gmq: revise

**Comment by lgaticaq** [comment]
Resuelto en #184
