### ISSUE TITLE
idea: un script para funcionalidades para usuarios golden :monea:

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#188]
en un dotENV losusuarios que han donado, osea los golden :monea: y que se construyan nuevas funcionalidades a los scrips si quien lo ejecuta esta en el archivo

**Comment by juanbrujo** [comment]
se me ocurre asi el flujo:
- alguien dona
- le indico a :huemul: quien fue
- :huemul: genera un token y una URL y envia por email al usuario, no se si el email lo puede rescatar de la api de slack?
- el usuario click en la URL, valida y publica en #comunidad quien es el nuevo usuario golden :monea: 
- el token expira
-. los golden :monea: duran sólo 60d y comenzaremos a crear scripts con funcionalidades extra para los golden :monea:

**Comment by lgaticaq** [comment]
El email lo envias por medio de paypal en el POST que envias a :huemul:

**Comment by lgaticaq** [comment]
@juanbrujo 

> :huemul: genera un token y una URL y envia por email al usuario, no se si el email lo puede rescatar de la api de slack?
El email tu ya lo tienes supongo de la info que te da Paypal o no?

**Comment by juanbrujo** [comment]
Si
