### ISSUE TITLE
idea: badge de :huemul: para scripts comprobado que funcionan en este bot

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#189]
que esté hosteado en un CDN y se coloque en el README de scripts usa :huemul:

**Comment by lgaticaq** [comment]
No entendi esta idea :thinking:

**Comment by juanbrujo** [comment]
si fueras golden :monea: entenderías

**Comment by hectorpalmatellez** [comment]
@lgaticaq Algo así, pero de :huemul:  
![badges](https://cloud.githubusercontent.com/assets/1266785/24060518/5a0e97ac-0b32-11e7-8831-91245e66bd7f.png)

**Comment by juanbrujo** [comment]
me refería que a anustros scripts pongamos un badge así: https://i.imgur.com/3n7BIJy.png

**Comment by juanbrujo** [comment]
este quedó mejor https://i.imgur.com/5iQih8N.png

**Comment by juanbrujo** [comment]
![huemul-approved](https://cloud.githubusercontent.com/assets/362186/24062435/52cc0b7a-0b3a-11e7-8c7f-215f9b481cf0.png)

**Comment by juanbrujo** [comment]
![screen shot 2017-03-17 at 17 51 10](https://cloud.githubusercontent.com/assets/362186/24062455/5e0a11d0-0b3a-11e7-8df0-0b0d45dfe627.png)

**Comment by lgaticaq** [comment]
Lo otro que es recomendable para hacer mas rápida la búsqueda de scripts es agregar una `keywords` en los `package.json` y un `topic` en el repo de github

**Comment by jlobos** [comment]
y algo así, cambiando al :unicorn: y de color cafe

[![](https://img.shields.io/badge/unicorn-approved-ff69b4.svg)]()

**Comment by lgaticaq** [comment]
@juanbrujo al final usaremos ![v1](https://i.imgur.com/5iQih8N.png) o este ![v2](https://img.shields.io/badge/huemul-approved-brightgreen.svg?style=flat-square)

**Comment by juanbrujo** [comment]
nosé creo que el segundo está mejor con la font.

**Comment by lgaticaq** [comment]
Ok la imagen es https://img.shields.io/badge/huemul-approved-brightgreen.svg?style=flat-square

**Comment by lgaticaq** [comment]
Hay una opcion de agregar el logo de huemul al lado izquierdo de huemul pero hay que dejarlo en blanco el logo y en data-uri
