### ISSUE TITLE
Agregar un linter y coverage

### ISSUE THREAD

**Issue by lgaticaq** [devschile/huemul#220]
En teoría podrían existir tanto un linter para js y coffee ([coffeelint](http://www.coffeelint.org/)).

**Comment by gmq** [comment]
Si es que se agrega debería ser uno que venga "hecho" en vez de estar peleando por qué reglas agregar. Algo como https://github.com/sindresorhus/xo o https://github.com/feross/standard

**Comment by lgaticaq** [comment]
@gmq xo usa tabs por defecto?

**Comment by gmq** [comment]
Si, pero se puede cambiar en el `package.json` de manera fácil
https://github.com/sindresorhus/xo#space

**Comment by lgaticaq** [comment]
:ban: xo, voto por standard

**Comment by gmq** [comment]
Igual hay varios que le ponen color por el `;`, se puede usar https://github.com/Flet/semistandard

**Comment by juanbrujo** [comment]
los que no usan `;` se les caen el pelo

**Comment by gmq** [comment]
Lo otro es que no sé si vale la pena agregar coffeelint. No se aceptan scripts en coffeescript y listo.
Si es 100% necesario usar coffee siempre se puede hacer un paquete externo.

**Comment by jlobos** [comment]
Estuve probando esta configuración con `xo`, `prettier` y `lint-staged` que les parece, el flujo de trabajo quedaría:

1. crear script o modificar existente
2. testear el codigo `npm test` o `yarn test`
3. agregar a git `git add .`
4. pasar el codigo por `prettier` antes del `commit` `npm run precommit` o `yarn run precommit`

el código saldría sin `semicolons`, solo con comillas simples `'` con espacios ` ` en lugar de tabs y ordenado al estilo de `prettier`

> esta configuración usa [now-cli](https://github.com/zeit/now-cli/blob/master/package.json) en producción

```json
  "scripts": {
    "start": "bin/hubot -a slack",
    "dev": "bin/hubot",
    "lint": "xo",
    "test": "npm run lint && ava",
    "precommit": "xo --quiet && lint-staged"
  },
  "engines": {
    "node": ">=7"
  },
  "xo": {
    "ignores": [
      "public/js/*",
      "test/*"
    ],
    "extends": "prettier"
  },
  "lint-staged": {
    "*.js": [
      "npm run lint",
      "prettier --single-quote --no-semi --write",
      "git add"
    ]
  },
```

**Comment by lgaticaq** [comment]
Yo dejaría el pretest para correr la validación de formato. De todas formas eso es lo mismo que hace standard o no? Aun no logro cachar para que usar prettier

**Comment by jlobos** [comment]
`prettier` seria mas que nada para que todos los scripts tengan el mismo formato de código o estructura

**Comment by lgaticaq** [comment]
por ejemplo si escribo estilo minificado mi codigo prettier lo dejaria formateado?

**Comment by jlobos** [comment]
claro, si tienes algo así:
```js
foo(reallyLongArg(), omgSoManyParameters(), IShouldRefactorThis(), isThereSeriouslyAnotherOne());
```
quedaría así:

```js
foo(
  reallyLongArg(),
  omgSoManyParameters(),
  IShouldRefactorThis(),
  isThereSeriouslyAnotherOne()
);
```
