### ISSUE TITLE
Agregar notificaciones de temblores

### ISSUE THREAD

**Issue by lgaticaq** [devschile/huemul#246]
La idea es usar el servicio [Earthquake Notification Service](https://earthquake.usgs.gov/ens/). Este servicio envía emails cuando ocurre un evento dado ciertos parámetros. Se puede usar mailgun o similar para crear una cuenta de email con webhook para de esa forma parsear el email en algún endpoint de :huemul: y de esa forma postear la alerta en algún canal de nuestro slack

**Comment by quest** [comment]
Yo podría enviar la información a algún webhook de huemul. Actualmente tengo una cuenta twitter que twitea temblores de chile, podría además de twitter, hacer un request a algún webhook o endpoint.

**Comment by juanbrujo** [comment]
tenemos Zapier para eso @quest podemos hacerlo sin problema

**Comment by quest** [comment]
ahh oka.

**Comment by lgaticaq** [comment]
en todo caso mejor usar un webhhok propio que zapier

**Comment by juanbrujo** [comment]
estoy trabajando en esto

**Comment by juanbrujo** [comment]
lo hice con zapier mejor, cerrando porque cumple.
