### ISSUE TITLE
fix: json no trae monedas los fines de semana en finvox.js

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#271]
https://github.com/devschile/huemul/blob/master/scripts/finvox.js

**Comment by rotvulpix** [comment]
Testing: June 10 (Sat) @ 3:23PM
huemul finvox btc
BTC: $1.899.069. La economía seguirá mal para ti, pero no para tu AFP. :moneybag:

**Comment by rotvulpix** [comment]
La api que se consulta "http://indicadoresdeldia.cl/webservice/indicadores.json" no trae esa info.

**Comment by rotvulpix** [comment]
Lo que podría hacer, es calcular el dólar en base a la info de los bitcoins:
Desde https://blockchain.info/es/ticker
```json
{
    "USD" : {"15m" : 2871.14, "last" : 2871.14, "buy" : 2870.13, "sell" : 2871.15,  "symbol" : "$"},
    "CLP" : {"15m" : 1905001.39, "last" : 1905001.39, "buy" : 1904331.26, "sell" : 1905008.03,  "symbol" : "$"}
}
```

Por lo tanto: Si BTC-USD: 2871.14 y BTC-CLP: 1905001.39
USD-CLP: 1905001.39 / 2871.14 = 663.5

Eso significa que usando la info real-time de BTC podriamos convertir entre diversas monedas. No solo USD-CLP.

Makes sense?
@juanbrujo

**Comment by JoseMCO** [comment]
lo otro sería usar la misma api pero en [XML](http://indicadoresdeldia.cl/webservice/indicadores.xml), que sí trae la info

```XML
<indicadores version="2,6" date="2017-10-01 11:30:04" url="http://indicadoresdeldia.cl/" author="Restart.cl Lab">
    (...)
    <moneda>
        <dolar valor="636.85" nombre="Dólar observado">$636,85</dolar>
        <dolar_clp valor="758.87" nombre="Dólar acuerdo">$758,87</dolar_clp>
        <euro valor="750.47" nombre="Euro">$750,47</euro>
    </moneda>
    <indicador>
        <ivp valor="23686.41" nombre="Indice de valor promedio (IPV)">$23.686,41</ivp>
        <uf valor="26658.56" nombre="Unidad de fomento (UF)">$26.658,56</uf>
        <ipc valor="0.2" nombre="Indice de Precios al Consumidor (IPC)">0,2</ipc>
        <utm valor="46786.00" nombre="Unidad tributaria mensual (UTM)">$46.786,00</utm>
        <imacec valor="2.8" nombre="Indicador mensual de actividad económica (IMACEC)">2,8</imacec>
    </indicador>
    (...)
</indicadores>
```

**Comment by juanbrujo** [comment]
pienso cambiar la fuente de la informacion a http://mindicador.cl/api/
