### ISSUE TITLE
🚨 Todavía hay ☕️ en :huemul: 🚨

### ISSUE THREAD

**Issue by hectorpalmatellez** [devschile/huemul#320]
¿Borramos ese archivo? :thinking-homer:

<img width="1006" alt="screen shot 2017-08-30 at 11 00 44 pm" src="https://user-images.githubusercontent.com/1266785/29902862-185cccde-8dd7-11e7-9b4d-a3704db824ea.png">

<img width="741" alt="screen shot 2017-08-30 at 11 01 17 pm" src="https://user-images.githubusercontent.com/1266785/29902877-2ab9128e-8dd7-11e7-873e-1c44c092d028.png">

**Comment by juanbrujo** [comment]
son los scripts de :pinceleart: :ql:

**Comment by lgaticaq** [comment]
👍
