### ISSUE TITLE
huemul steam no calcula bien los valores de los juegos

### ISSUE THREAD

**Issue by chrisdelcaos** [devschile/huemul#322]
Hola Chicos,

como dice el titulo, la instrucción del juego para Steam con Huemul en producción no esta calculando los valores de forma correcta, además de cortar el ultimo dígito de los valores originales y rebajados. Podrían mirar que pasó en el cambio de desarrollo a producción?

gracias y saludos.

**Comment by gmq** [comment]
Como el servidor está en USA está tirando los valores en dólares.

**Comment by juanbrujo** [comment]
:wntard: aer

**Comment by chrisdelcaos** [comment]
@gmq toda la razón xd

**Comment by chrisdelcaos** [comment]
[https://github.com/devschile/huemul/pull/324](url)

**Comment by lgaticaq** [comment]
Ya esta resuelto
