### ISSUE TITLE
Calendario: elegir mes/año

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#432]
`huemul calendario julio` -> muestra calendario julio presente año
`huemul calendario julio 2020` -> muestra calendario julio año 2020

**Comment by catagranic** [comment]
`huemul calendario julio` -> muestra calendario junio presente año
`huemul calendario junio` -> muestra calendario junio presente año
`huemul calendario marzo 2020` -> muestra calendario junio presente año 

Todo está devolviendo calendario junio presente año.

**Comment by juanbrujo** [comment]
@raerpo todo tuyo, es fácil este
