### ISSUE TITLE
noticias.js TAMALO

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#437]

**Comment by lgaticaq** [comment]
Por lo visto dieron de baja esa url y no logro pillar un buscador en 24horas. Habrá que cambiar de fuente o bien dar de baja el script

**Comment by juanbrujo** [comment]
si, 24hrs no tiene ya. Mega noticias si, comencé a hacerlo pero no terminé. Te paso la url:

view-source:http://www.ahoranoticias.cl/home/

linea 374

**Comment by lgaticaq** [comment]
La consulta es:

```javascript
robot
  .http('http://www.ahoranoticias.cl/buscador/')
  .header('Origin', 'http://www.ahoranoticias.cl')
  .header('Accept-Encoding', 'gzip, deflate')
  .header('Accept-Language', 'es-419,es;q=0.9')
  .header('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8')
  .header('Accept', 'text/html, */*; q=0.01')
  .header('Cache-Control', 'no-cache')
  .header('X-Requested-With', 'XMLHttpRequest')
  .header('Referer', 'http://www.ahoranoticias.cl/home/')
  .post({ q: 'mundial', ajax: true })
```

Lo anterior entrega html con 3 resultados.

También esta la url http://www.ahoranoticias.cl/buscador/?q=mundial la cual puede entrega 12 resultados por paginas

**Comment by rcarmonad** [comment]
que pasa si en ves de pegarle a esas noticias, le pegamos al dixit.io?

**Comment by juanbrujo** [comment]
voh dale, pegale al buscador directo `https://dixit.io/week?q=backend ql`

**Comment by rcarmonad** [comment]
Empece, sin hacer un feature, a revisar la alternativa de dixit.
Desde cero usando cheerio, pero cuando le pego al sitio, me rentorna errores.
Veré que sucede.

**Comment by juanbrujo** [comment]
@rcarmonad OJO ya hay un PR sobre esto https://github.com/devschile/huemul/pull/472

**Comment by juanbrujo** [comment]
este PR lo cierra https://github.com/devschile/huemul/pull/472

**Comment by rcarmonad** [comment]
Si cache
--
*Rodrigo Carmona Donoso*
*Software Developer*
Móvil: (+569) 9966 1529
rcarmonad@gmail.com
