### ISSUE TITLE
Agregar LUK a orionx.js

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#443]
@gmq no tengo las keys para probar local, pero debe ser fácil agregar LUK al script https://github.com/devschile/huemul/blob/master/scripts/orionx.js no?

`luk: 'LUKCLP',`

**Comment by gmq** [comment]
@juanbrujo  Si, con eso debería bastar

**Comment by juanbrujo** [comment]
@gmq tienes como comprobar? o lo hago yo a la vida a ver si funciona?
