### ISSUE TITLE
agregar excepciones explícitas al karma

### ISSUE THREAD

**Issue by davidlaym** [devschile/huemul#468]
uno habla de c++ y el :ql: dice que no existe el usuario c++

**Comment by davidlaym** [comment]
Asignemne pls, tengo un PR en progreso

**Comment by juanbrujo** [comment]
listoco

**Comment by juanbrujo** [comment]
duplicado? https://github.com/devschile/huemul/issues/203

**Comment by davidlaym** [comment]
diría que el caso de los snippets no se arregla con excepciones, ahí si hay muchos más casos posibles de mal interpretación

**Comment by juanbrujo** [comment]
solucionado en https://github.com/devschile/huemul/pull/469#event-1895741987
