### ISSUE TITLE
script de bienvenida dejó de funcionar

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#473]
hace harto https://github.com/devschile/huemul/blob/master/scripts/saluda.js ya no le escribe a los nuevos, entran y no cachan nada del eslac. hay que revisar qué cambió en la API.

**Comment by lgaticaq** [comment]
Hice pruebas con `guemul` cambiando el channel a #juegos he hice pruebas entrando a ese canal (join) y envía el mensaje bien

**Comment by lgaticaq** [comment]
:ya: es por el tipo de canal que es #anuncios. Como es solo lectura no permite el `robot.enter`. La solución es cambiar el canal del script a otro normal en donde este invitado :huemul:

**Comment by juanbrujo** [comment]
pero confirmaron que #comunidad es un canal obligatorio que todos entran?

**Comment by lgaticaq** [comment]
Si, hice pruebas con nuevos usuarios

**Comment by lgaticaq** [comment]
También estaba backend pero corría peligro que mergearan el PR, demaciados fronen tienen que aprobar

**Comment by juanbrujo** [comment]
este PR lo cierra https://github.com/devschile/huemul/pull/474
