### ISSUE TITLE
Portadas: Diario de San Felipe

### ISSUE THREAD

**Issue by hectorpalmatellez** [devschile/huemul#513]
http://www.eltrabajo.cl/slide/diariojpg.htm

http://www.eltrabajo.cl/slide/eltrabajo%20(1).jpg

https://www.facebook.com/ElTrabajoDiario/

**Comment by juanbrujo** [comment]
hay alquien de san felipe que lo veria?

**Comment by juanbrujo** [comment]
https://github.com/devschile/huemul/pull/525 soluciona esto admin re100kl flojo
