### ISSUE TITLE
Get current year progress percentage

### ISSUE THREAD

**Issue by hectorpalmatellez** [devschile/huemul#524]
http://progressbarserver.appspot.com/
https://twitter.com/year_progress

**Comment by juanbrujo** [comment]
hazlo po si tiempo tenis

**Comment by hectorpalmatellez** [comment]
y si no kiero k

**Comment by juanbrujo** [comment]
admin flojo kl

**Comment by Zenemig** [comment]
Puedo ver esto, pero no cacho bien como comunicarme con el bot/slack y toda esa paja.

**Comment by juanbrujo** [comment]
@Zenemig usa moment, tiene esos metodos y ya esta instalado

**Comment by Zenemig** [comment]
Dale, en la casa sapeo que onda, molesto cualquier duda.

**Comment by juanbrujo** [comment]
http://momentjs.com/docs/#/displaying/fromnow/

**Comment by Zenemig** [comment]
Si esa parte la cacho, lo que no cacho es la parte bot/slack del script. Recibir el comando y devolver la respuesta, pero me imagino que mirando los otros scripts + documentación puedo ir cachando

**Comment by juanbrujo** [comment]
hecho en https://github.com/devschile/huemul/pull/536
