### ISSUE TITLE
tarea: Organizar los encabezados de los scripts

### ISSUE THREAD

**Issue by raerpo** [devschile/huemul#552]
El comando `huemul help` muestra el encabezado de todos los scripts usados. En este momento están desorganizados y muestran la ayuda sin consistencia en incluso en ingles.

La idea seria hacer un script para el package json que genere el formato correcto de ayuda para un script. De pronto usando inquirer o commander para hacer un interfaz interactiva.

**Comment by juanbrujo** [comment]
creo que esto ya se hizo no?

**Comment by raerpo** [comment]
no. Este issue no prendio.
Aún no se si les parecia una idea valida para comenzar a trabajarla 🤷‍♂

**Comment by juanbrujo** [comment]
@lgaticaq estuvo organizando los encabezados de los scripts, revisa denuevo a ver si falta algo plis
