### ISSUE TITLE
fix: temblores no retorna por localidad, si general.

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#553]
![Screen Shot 2019-05-30 at 10 15 03](https://user-images.githubusercontent.com/362186/58638951-f27ca780-82c3-11e9-881c-bd4d02da428b.png)

**Comment by raerpo** [comment]
No lo pude reproducir pero si note que solo funciona poniendo el nombre de los lugares en ingles.
Será eso a lo que se refiere el bug?

<img width="616" alt="Screen Shot 2019-06-08 at 7 17 57 PM" src="https://user-images.githubusercontent.com/1649463/59153224-270a0500-8a22-11e9-87f4-34e085cf1e34.png">

**Comment by juanbrujo** [comment]
si puede ser... quizas haya que especificar eso en el `Commands` para el help.
