### ISSUE TITLE
huemul tupoto retorna un 404

### ISSUE THREAD

**Issue by sebaLinares** [devschile/huemul#563]
El comando `huemul tupoto <url>` retorna un 404. Revisé en [tupo.to](www.tupoto.to) y el request se hace a `www.tupo.to/.netlify/functions/post` (funciona bien) y en el script huemul se está haciendo a `https://tupo.to/`.

Cuando lo cambio a `...netlify/functions/post` retorna `Toma tupo.to: undefined` + 4 caracteres alphanuméricos + `%`, por ej: `Toma tupo.to: undefined3V5q%`.

**Comment by lgaticaq** [comment]
El request ahora se debe ejecutar de la siguiente forma:

```bash
curl -X POST https://tupo.to/.netlify/functions/post -H "referer: https://tupo.to/" -d '{"uri": "https://devschile.cl/"}'
```

Eso retorna:

```bash
https://tupo.to/XDI6
```

Es necesario agregar el header **referer** ya que esta pensado para ser usado desde netlify usando `functions`.

Para extraer el hash se debiera usar algo asi:

```js
const match = /https?:\/\/tupo.to\/(\w+)/.exec('https://tupo.to/XDI6')
```
