### ISSUE TITLE
test de uoct-golden da errores random

### ISSUE THREAD

**Issue by lgaticaq** [devschile/huemul#604]
Hace un par de días esta pasando que al correr los test ocurren errores random. Estos pueden ser revisados en los logs de builds en travis.

**Comment by davidlaym** [comment]
Según pude revisar, los errores se deben a un problema de timing o condición de carrera al hacer el `deepEquals` del `postMessage.options`. Segun el `beforeEach` configurado, se debería llenar `t.context.postMessage` con el resultado del mensaje enviado, pero en este caso, resulta `undefined`.
Revisé que efectivamente es aleatorio y no siempre fallan los mismos tests en las mismas condiciones.

Intenté hacer un mock directo de `postMessage` en el test mismo y pareciera que funcionó, pero esto en realidad no veo que arregle nada definitivamente. Creo que podría agregar alguna promesa que se resuelva una vez que se reciba el mensaje en  `postMessage`, pero quería ver si tenían una idea mejor para corregir esto.
