### ISSUE TITLE
Modificar tusecreto.js para disponibilidad en más canales

### ISSUE THREAD

**Issue by iamravenous** [devschile/huemul#68]
Partiendo de la idea de hacer un clon del script _tusecreto.js_ para que funcione en el canal #pegas, está la posibilidad de adaptar el script para que soporte variabilizar el canal de destino, lo que sería ideal para darle más versatilidad y contexto a esta funcionalidad de huemul.

**Comment by juanbrujo** [comment]
eso si, si no se define un canal que postee en #random por defecto.

pd. :jaime: no te cambies de pega.

**Comment by lgaticaq** [comment]
@iamravenous hace tiempo propuse eso pero llegamos a la conclusión que seria un caos. No se cual es la postura actual de la junta directiva

**Comment by jaimeguaman** [comment]
estaba muy volao o un día vi que enviaban secretos a otros canales? 
osea la funcionalidad está y la rechazaron por caotica?

**Comment by iamravenous** [comment]
Estabas muy volado, solo era un `huemul echo`.

**Comment by iamravenous** [comment]
@lgaticaq Ahora mismo se estaba conversando en #huemul-devs, por eso lo puse acá.

**Comment by hectorpalmatellez** [comment]
jaime-- por volao

**Comment by juanbrujo** [comment]
_react culiao eres más feo que vender créditos a abuelitos_

**Comment by juanbrujo** [comment]
_react, escucha, ándate a la chucha_

:wntard:
