### ISSUE TITLE
agencias.js: agregar posibilidad de remover algun git del listado

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#75]
a veces se han equivocado y agregado gif's por la URL del servicio y no del gif mismo. sería cool poder remover algún gif para ir renovándolos también.

**Comment by lgaticaq** [comment]
En el pull request viene eso

**Comment by juanbrujo** [comment]
_El comando entrega una url para poder visualizar, *eliminar* y corregir las imágenes _ :wntard: Gracias!
