### ISSUE TITLE
Investigar por qué huemul tira lo primero al final y al final lo primero

### ISSUE THREAD

**Issue by hectorpalmatellez** [devschile/huemul#83]
Por ejemplo:
<img width="632" alt="screen shot 2016-11-03 at 11 55 36 pm" src="https://cloud.githubusercontent.com/assets/1266785/19992994/0a7a2c76-a221-11e6-92fd-23301ae4e85a.png">

**Comment by rotvulpix** [comment]
En qué casos pasa? Aparte del de las recetas, algo ví pero no estoy seguro

**Comment by hectorpalmatellez** [comment]
@rotvulpix 👇 
<img width="474" alt="screen shot 2016-11-11 at 11 17 46 pm" src="https://cloud.githubusercontent.com/assets/1266785/20234987/24ea6fb8-a865-11e6-94de-3db5d6bcfb6c.png">

**Comment by juanbrujo** [comment]
siempre pasa en todos los scripts

**Comment by lgaticaq** [comment]
Descubrí el error. Solo ocurre cuando se envían varios res.send en vez de solo uno. Y que se cumpla la condición de que esas respuestas incluyan enlaces y/o imágenes. Como slack tratara de resolver esos enlaces tardara mas en responder eso que los textos. La solución, armar un string con la respuesta final y enviar un solo res.send.

**Comment by juanbrujo** [comment]
pero, porque pasa aqui? en otro slack con los mismos no sucede.

**Comment by lgaticaq** [comment]
Será por la carga? En verdad no sabría por qué aquí pasa y en otro slack no. Cuando tenga tiempo haré PR de los script que presentan problemas con la solución que propuse

**Comment by juanbrujo** [comment]
creo que es culpa de :pinceleart: o de :jaime: seguro algo hicieron BAN

**Comment by hectorpalmatellez** [comment]
👏

**Comment by juanbrujo** [comment]
porque lo cerraste :hector: ? No está solucionado :/
